### ISSUE TITLE
New template system

### ISSUE THREAD

**Issue by Shnoulle** [Shnoulle/LimeSurvey-Shnoulle#19]
According to 2016-09-06 team meeting, i think we can
- remove template-test directory
- rename the old template to olname_old
- create a new default with less css/js
- create a new 'lighter' template : no awesome , just bootstrap.css, no js etc ....
- create a new 'lighter' template with awesome
- With this 2 ligthter template replace default bootsrtrap file by one of bootswatch (Cerulean for example)

Then when we are ready, we can release easily  : 
- default (awesome) : bootstrap based only ?
- default no awesome
- cerulean
- Cosmo
- Human
- ..... any boostrap theme file 

I make this today if you OK.

**Comment by Shnoulle** [comment]
@PeterEmil  : OK ? removing actual template, keed it for testing purpose (to see if user can update easily and quickly)

**Comment by PeterEmil** [comment]
That's a good step forward! I'm OK with the proposal :)
When I can step in and take some off your shoulder don't hesitate to ask!

**Comment by LouisGac** [comment]
I like the idea of the 'lighter'  being pure bootstrap.css with no js.

**Comment by PeterEmil** [comment]
The default-to-be template will function as the ultimate master - for developing & theming purposes. Perhaps good idea to coin it "core", or "base"? Or keep the name "default" but then it is only vanilla Bootstrap, no flavouring.

**Comment by LouisGac** [comment]
> Perhaps good idea to coin it "core", or "base"

I really don't see the interest of forcing a core template to be the base of any other templates.
IMHO, if someone for any reason want to start from scratch, it should be possible. 

If it's just about naming: yep core, base, _blank, whatever you'd like.

**Comment by PeterEmil** [comment]
>if someone for any reason want to start from scratch, it should be possible
Well, that's exactly what we're after :)

The essence is clean HTML & CSS so it acts as a base.

**Comment by LouisGac** [comment]
_vanilla template_: could be a nice name? 
whatever: you're doing it, feel free to name it.

**Comment by Shnoulle** [comment]
Some are here https://github.com/Shnoulle/LimeSurvey-Shnoulle/tree/answers_html/templates

I must remove the include EM too ....

**Comment by tammoterhark** [comment]
What I hope to achieve: there are one or more very basic templates (just bootstrap, perhaps one with awesome things in it, another one without). They could for example be called:
* base
* base_awesome
* ...

and each user can decide to use one of these templates as a basis for further development by adding something like: <basetemplate>base</basetemplate> to the config.xml of his own template: "mytemplate"

After doing that a file like template.css in the child theme could have only one statement: body{background-color:yellow} because the template will use (1) all defined css files in the base template and after that use the templates own template.css which overrides the body statement of the base template.

As for .pstpl files: if a .pstpl file is available in "mytemplate" it will be used, otherwise .pstpl files from "base" will be used. Same for question views files: if they are prersent, they will override what is defined in core, otherwise core question views will be used.

And if some clever guy (where are the girls?) does not want a child template, he can start by copying "base" to "my_copy _of_base" and reshape that to anything he wants. And even create children from that. But this way he looses clever additions that the development team adds to the base template.

In this approach the current "default" template is a child of the "base"template, with some styling to make it look exactly like the current "default". Same for "Ubuntu Orange" and the other one.

And also Denis and Peter Emil can use "base" as a basis for futher development. But they may also use "base-awesome" or create their own "mother" template, but then they will not synchronize with what is added to "base" because "base" will reflect everything that is added to LimeSurvey core.

Is this also what you all mean with this new approach?

**Comment by LouisGac** [comment]
for me it seems very ok.

**Comment by tammoterhark** [comment]
Louis: when can you work on a system of making child templates possible?

**Comment by LouisGac** [comment]
it's rather a feature request. 

Right now I'm coding a Joomla component to port limeservice functionalities to limesurvey.org. Then I must finish the migration application (a Yii app to merge the two databases). Then I'll have time.
So for now, you should dev the templates without the child feature.... 

unless you convince carsten that I should work on it asap during next meeting

**Comment by tammoterhark** [comment]
OK, but it means we may have to adapt the current default & others first (to reflect changes in question views) and after that rebuild default & others to be based on base. Or we could just leave that away, but that would burden the development team with keeping multiple templates up to date. For now: let's concentrate on making the question views as clean as possible.

And in base template: make the pstpl files as clean as possible.

**Comment by Shnoulle** [comment]
Remind : actual milestone . I don't have time to review the default template. Else waiting for 2 month more.

**Comment by tammoterhark** [comment]
Let's see how we can tackle this. I do not like to wait two months before I can make use of everything that Denis and Peter Emil are developing now.

**Comment by Shnoulle** [comment]
Actual situation

- I update totally the html to be Bootsrap only + awesome compliant 
- Testing HTML update with only base_awesome
- Then after all fixed : can remove all no bootsrap + awesome from default 
- And then add the little fix.

See for example
- http://testing.sondages.pro/answershtml/alternate/awesome/index.php/15348
- http://testing.sondages.pro/answershtml/alternate/awesome/index.php/15348?lang=fr&encode=

This use only bootstrap. I think it's more easy to fix template css one time for all aftger

**Comment by tammoterhark** [comment]
Did you work all night?
