### ISSUE TITLE
Css class specific fo LimeSurvey

### ISSUE THREAD

**Issue by Shnoulle** [Shnoulle/LimeSurvey-Shnoulle#31]
We actually use boostrap + some old class from 2.06/1.82 version.

1st question is : for LimeSurvey class : do we need to add a ls- before : for example

````
.ls-answer-item
.ls-radio-item
````

This replace whole older class : https://manual.limesurvey.org/The_template_editor#Global_classes_for_question_part

Some more question : we have errormandatory answertext etc .... maybe it's better to have error-mandatory answer-text subquestion-text etc .... Did we need it in thead tr th : we don't have it in 2.06, @LouiGac add some : when i see it think it's a good idea (with clean separation between answer-text and (sub)question-text). For (sub)question-text : some template use question-text for the wrapper of question text. Then the name is not good (see the 1st question to don't have this issue)

error/success : Expression Manager add error/success class, and only this : it must be : extendable (adding alert alert-danger for example) + core class : em-error / em-success ?

**Comment by LouisGac** [comment]
1. Prefixing class by ls would be nice (it's kind of "namespace"), but it's not really necessary, and it could take quiet a long time. So again, it's up to you and tammo to choose. 

2. Same for the 'error-mandatory' instead of 'errormandatory'. It would be a good thing (it's more readable), but long and unnecessary. 

3. Imho: the best system is to have an error system for the whole question + an error system for each input in the question (if many, like in arrays, or multiple numerical, etc). 

4. If we change the EM, I'd say we should rather just raise an event and let another component deal with what to do (in the futur: plugins, templates, question object, etc ; for now: core js? question specific js?).

**Comment by Shnoulle** [comment]
For 4 :+1:  . 

For other, i see with Tammo.

Think have "bootstrap" class + no nnamespce class it's OK. In fact : i don't like errormandatory and answertext : not necessary, but really more readable to have error-mandatory / answer-text. A `sed` on views/survey/question directory can surely do the trick for some. And it's better if we do it before 3.x release.

**Comment by LouisGac** [comment]
sed is dangerous, but can be checked in the commit with diff.

**Comment by Shnoulle** [comment]
I say for some . You think we can have answertext for other purpose than class or comment ?

PS : what do you think about the subquestion text ? It's not really answer-text. I see you added some th-X : but don't understand the pupose .

**Comment by Shnoulle** [comment]
For 3: it's already the idea : 

- input-error in {QUESTION_INPUT_ERROR_CLASS} : https://github.com/Shnoulle/LimeSurvey-Shnoulle/blob/answers_html/templates/default/views/question.pstpl#L2 (maybe , when we have time add (minmax-error|mandatory-error|blablafrmem-error)
- form-group has-error for "subquestion line" https://github.com/Shnoulle/LimeSurvey-Shnoulle/blob/answers_html/templates/default/views/question.pstpl#L2  . Must be readded at some place : but if it's not done in 3.0 : we can fix it in a minor release (it's a bug) .

**Comment by Shnoulle** [comment]
Started : https://github.com/LimeSurvey/LimeSurvey/commit/15bf9e7bc04dd765a7e9b60c5755c50eac83c9f6

**Comment by Shnoulle** [comment]
OK, added some ls- + add some question- etc ....
