### ISSUE TITLE
Feature request : unsure about final decison

### ISSUE THREAD

**Issue by Shnoulle** [Shnoulle/LimeSurvey-Shnoulle#32]
I put 5 feature request in mantis (because mantis is done for this too)

Please :up/down vote

- input size https://bugs.limesurvey.org/view.php?id=11734 : reimplement a real input size attribute, and some css core for it : need to add a new attribute.
- https://bugs.limesurvey.org/view.php?id=11726 column width and answer width in multiple question : have same size (by default) for all table and line of subquestion (text and numeric). Actually we have 20%, 40% or 50% by default for answer width in table, and col-sm-6 for answer width in mutiple text and numerci : think beter to have same size (col-sm-3 / 33%) by default
- https://bugs.limesurvey.org/view.php?id=11724 input-group-addon for suffix/prefix : great or not ? Can be done in template : maybe more a template issue, don'yt =know here
- https://bugs.limesurvey.org/view.php?id=11725 : slider oin same line than subquestion (like in 2.06) in big screen
- https://bugs.limesurvey.org/view.php?id=11660 : for this none : no issue, can be done in 3.1

@tammoterhark , @tpartner , @maziminke , @LouisGac : sorry for mail bombing, but some decision are unclear :) Vote seems the best way.

Edit : lost a feature

**Comment by Shnoulle** [comment]
For https://bugs.limesurvey.org/view.php?id=11724 : added ls-input-group-extra class, test in short text (+ multiple lines). To be confirmed before apply elsewhere. If someone have another great idea.

**Comment by LouisGac** [comment]
> Vote seems the best way.

Well, when things are blocked, I'd say that the one who codes should be free to choose. So, in my point of view, if you feel able to do all the changes you requested, you should be free to do them. 

Else, point by point:
1. "_leave text_input_width to set the input container width_" 
I think it's an excellent idea. It would make easy for user to build new layout with for example 2 questions side by side, and another one on the bottom

2. "_have same size (by default) for all table and line of subquestion (text and numeric)_"
Agree, should make it more coherent 

3. "i_nput-group-addon for suffix/prefix : great or not ? Can be done in template : maybe more a template issue, don'yt =know here_"
I think it's depend if it's easy to do. If it's easy to move it to template: great. 

4. "_slider oin same line than subquestion_"
If I remember well, the problem is rather the length of question. Right now, you can do it by setting a width for the question. So, it's about choosing a minimal length for the slider. 

5. "_Adding number of colmun in table of question class [...] so some user can deactivate no-more-tables if array have 2 column (for example)._"
Adding user control is always a good thing.

**Comment by Shnoulle** [comment]
Hi,

> I'd say that the one who codes should be free to choose.

Yes, and no ... because it's used by a lot of user's and after we have bug report/feature request. Let me explain : 

1. actually no-js functionnality it's not a core issue : if someone post a no-js bug : it's not a bug. I made the choice to support no-js. If another dev break a no-js functionnality in a feature: i'm responsible to fix no-js without breaking functionnality.
2. radix is a core feature : if someone break a radix functionnality in a feature : he's responsible for fixing it, someone can do it before, but he still responsible.


In fact : i can allways quit the LS team, but if i want to stay : i'm responsible :smile:
